### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by fredcw** [fredcw/Notes#9]
[graphite.zip](https://github.com/fredcw/Notes/files/14626895/graphite.zip)

[fluent_theme.zip](https://github.com/fredcw/Notes/files/14626897/fluent_theme.zip)

[asd.zip](https://github.com/fredcw/Notes/files/14746966/asd.zip)

**Comment by fredcw** [comment]
@mtwebster I've taken an existing gtk theme, "Fluent", and I'm writing a python script to make the theme options easy to use with a gui with the idea that a "theme options" button could be available in system settings>themes for themes which have such a script in them. But atm (in cinnamon) I'm having to rename the theme each time it's updated because I can't find a way to get the wm to reread a changed theme (window decorations), it seems to be caching the theme somehow so that any changes are ignored. Any idea how I can do this without renaming the theme? Using gsettings to reset 'org.cinnamon.desktop.interface gtk-theme' and set it back again reloads the gtk theme but not the window decorations theme.
[fluent_theme.zip](https://github.com/fredcw/Notes/files/14325127/fluent_theme.zip)

The file `options.py` in the theme directory would be run by the user, or the file ./config/config_gui.py would be imported by the os to make the options available to the user.

**Comment by mtwebster** [comment]
Hi, for Cinnamon at least you could try `cinnamon-dbus-command ReloadTheme`.  You can use that utility to make any call described in `js/ui/cinnamonDBus.js`

**Comment by fredcw** [comment]
Thanks, but it seems that this only updates the cinnamon theme `org.cinnamon.theme  name` which has no effect on the theming of window decorations of windows which don't have CSDs, what would previously have been styled by the metacity theme and now seems to be styled by the gtk-3.0 theme since the muffin rebase. Only restarting cinnamon or giving the theme a new name seems to work. Resetting `org.gnome.desktop.interface gtk-theme` works with GNOME but not with cinnamon, so not sure what the difference is there.
